spring:
  application:
    name: NEWSAPP-USER-PROFILE-SERVICE
  config:
    import: configserver:http://newapp-lb-1016212984.us-east-1.elb.amazonaws.com:8888
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://shilpadb1.cgfmsjhynal8.us-east-1.rds.amazonaws.com:3306/userdb?createDatabaseIfNotExist=true
    username: admin
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
      properties:
        dialect: org.hibernate.dialect.MySQL8Dialect
  doc:
    swagger-ui:
      path: /swagger-ui

  kafka:
    bootstrap-servers: ec2-13-200-244-97.ap-south-1.compute.amazonaws.com:9092

server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://newapp-lb-1016212984.us-east-1.elb.amazonaws.com:8761/eureka/
